### ISSUE TITLE
Test code

### ISSUE THREAD

**Issue by ExitPath** [minjoong507/Image-Captioning-Transformer#1]
Excuse me, can you provide the code of the test process? The input of the test is only an image and does not require the target caption.

**Comment by minjoong507** [comment]
Hi @ExitPath 

Do you mean the test code for test dataset?

**Comment by ExitPath** [comment]
> Hi @ExitPath
> 
> Do you mean the test code for test dataset?

Yes, it is test.py or eval.py. The input is just an image，and the predicted caption can be output.

**Comment by minjoong507** [comment]
Sure. Maybe I can upload the inference.py for evaluation within next month. I'll let you know when I'm done with work.

**Comment by ExitPath** [comment]
Ok, thank you very much！

**Comment by minjoong507** [comment]
Hi @ExitPath 

I upload the inference.py. Please check the repo and let me know if you have any problem.

Thanks :)
